import { Car, BlogPost } from './types';

// Define static path strings for our custom generated photography assets
const bugattiImg = '/src/assets/images/bugatti_tourbillon_studio_1784132351413.jpg';
const paganiImg = '/src/assets/images/pagani_utopia_sunset_1784132367624.jpg';
const koenigseggImg = '/src/assets/images/koenigsegg_jesko_track_1784132384055.jpg';

export const CARS: Car[] = [
  {
    id: 'bugatti-tourbillon',
    brand: 'Bugatti',
    model: 'Tourbillon',
    year: 2026,
    price: 4600000,
    priceString: '$4.6 Million',
    image: bugattiImg,
    category: 'Hypercar',
    origin: 'France',
    engine: '8.3L Naturally Aspirated V16 + 3 Electric Motors',
    power: 1800,
    torque: 1600,
    topSpeed: 276,
    acceleration: 2.0,
    weight: 1995,
    productionVolume: 250,
    chassis: 'Monolithic Carbon Fiber Monocoque',
    transmission: '8-Speed Dual-Clutch Automatic',
    drivetrain: 'AWD',
    highlights: [
      'Engine revs to an astronomical 9,500 RPM',
      'Swiss-made titanium tourbillon instrument cluster',
      'No digital screens visible on the center console by default',
      'Carbon-fiber composite body with integrated diffuser'
    ],
    description: 'The Bugatti Tourbillon represents an absolute paradigm shift. Moving away from the quad-turbocharged W16 era, Bugatti has engineered a clean-sheet 8.3-liter naturally aspirated V16 engine in partnership with Cosworth. Combined with three electric motors (two on the front axle and one on the rear), this hybrid powerhouse delivers a combined 1,800 horsepower. It is a masterpiece of both horology and speed, featuring an instrument cluster crafted by Swiss watchmakers, where gear trains actuate analog dials with jewel-like precision.',
    designEthos: 'A fusion of haute horlogerie and aerospace aerodynamics. The center console is made of solid crystal glass and aluminum, while the steering wheel features a fixed-hub steering system where the gorgeous gauge cluster remains stationary as you turn the wheel.',
    aeroFeatures: 'Incorporates a hidden retractable active rear wing that functions as an airbrake, a ground-effect venturi tunnel floor, and advanced active front diffusers.'
  },
  {
    id: 'pagani-utopia',
    brand: 'Pagani',
    model: 'Utopia',
    year: 2024,
    price: 2500000,
    priceString: '$2.5 Million',
    image: paganiImg,
    category: 'Hypercar',
    origin: 'Italy',
    engine: '6.0L Twin-Turbocharged V12 (AMG)',
    power: 864,
    torque: 1100,
    topSpeed: 220,
    acceleration: 3.0,
    weight: 1280,
    productionVolume: 99,
    chassis: 'Carbo-Titanium & Carbo-Triax HP62 Monocoque',
    transmission: '7-Speed Gated Manual / Automated Manual',
    drivetrain: 'RWD',
    highlights: [
      'Gated 7-speed manual transmission linkage exposed',
      'Bespoke AMG 6.0L V12 with zero hybridization',
      'Exquisite titanium quad-exhaust sculpture',
      'Weighs only 1,280 kg—lighter than most compact hatchbacks'
    ],
    description: 'The Pagani Utopia is Horacio Pagani’s response to the digital overload of the modern automotive world. Eschewing heavy battery packs, dual-clutch gearboxes, and large touchscreens, the Utopia is a love letter to mechanical purity. It features a bespoke Mercedes-AMG 6.0-liter twin-turbo V12 producing 864 horsepower, channeled directly to the rear wheels via a gated 7-speed manual transmission. The interior is an art gallery of milled aluminum, premium hand-stitched leather, and exposed gear linkages.',
    designEthos: 'An aesthetic dialogue inspired by 1950s aerospace, high-end Swiss horology, and the Renaissance drawings of Leonardo da Vinci. Every switch is a machined toggle; every dial is analog.',
    aeroFeatures: 'Strap-on active aero flaps integrated into the rear deck lid, air tunnels channeling high-velocity air through the body, and active suspension to manage roll and pitch.'
  },
  {
    id: 'koenigsegg-jesko',
    brand: 'Koenigsegg',
    model: 'Jesko Attack',
    year: 2025,
    price: 3000000,
    priceString: '$3.0 Million',
    image: koenigseggImg,
    category: 'Track Weapon',
    origin: 'Sweden',
    engine: '5.0L Twin-Turbocharged V8 (E85 fuel)',
    power: 1600,
    torque: 1500,
    topSpeed: 310,
    acceleration: 2.5,
    weight: 1420,
    productionVolume: 125,
    chassis: 'Carbon Fiber with Kevlar reinforcement',
    transmission: '9-Speed Light Speed Transmission (7 Clutches)',
    drivetrain: 'RWD',
    highlights: [
      '9-speed Light Speed Transmission shifts in milliseconds',
      'Produces up to 1,400 kg of high-velocity downforce',
      'Flat-plane crank V8 revs with terrifying speed',
      'Triplex suspension system with active rear-wheel steering'
    ],
    description: 'The Koenigsegg Jesko Attack is a relentless pursuit of pure speed and track domination. Named after Christian von Koenigsegg’s father, the Jesko features an in-house engineered 5.0-liter twin-turbo V8. When running on E85 biofuel, it produces an astonishing 1,600 horsepower. The power is transmitted through Koenigsegg’s revolutionary Light Speed Transmission (LST)—a 9-speed, 7-clutch unit that allows shifting from any gear to any gear instantaneously (e.g., 7th to 4th without intermediate steps).',
    designEthos: 'Extreme fighter-jet inspired canopy. The carbon fiber chassis is ultra-rigid, and the cabin features a steering wheel with integrated touchscreen dials that rotate with the wheel.',
    aeroFeatures: 'A colossal active top-mounted dual-stage rear wing, massive front splitter, and active underbody flaps generating ground-suction venturi effects.'
  },
  {
    id: 'ferrari-daytona-sp3',
    brand: 'Ferrari',
    model: 'Daytona SP3',
    year: 2023,
    price: 2250000,
    priceString: '$2.25 Million',
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80',
    category: 'Hypercar',
    origin: 'Italy',
    engine: '6.5L Naturally Aspirated V12',
    power: 829,
    torque: 697,
    topSpeed: 211,
    acceleration: 2.8,
    weight: 1485,
    productionVolume: 599,
    chassis: 'F1-Derived All-Carbon Composite Chassis',
    transmission: '7-Speed Dual-Clutch Automatic',
    drivetrain: 'RWD',
    highlights: [
      'Most powerful pure ICE naturally aspirated V12 from Ferrari',
      'Stunning wrap-around windscreen reminiscent of 1960s sports prototypes',
      'Exquisite horizontal rear strake styling elements',
      'Limited production reserved strictly for elite collectors'
    ],
    description: 'The Ferrari Daytona SP3 is a masterpiece of the Icona series, paying tribute to the legendary 1967 24 Hours of Daytona where Ferrari took a legendary 1-2-3 finish. It features a mid-mounted, naturally aspirated 6.5-liter V12 engine that screams all the way to 9,500 RPM, producing a visceral, bone-chilling exhaust note. Its carbon fiber chassis is derived entirely from Formula 1 technology, creating a deeply connected, physical driving experience.',
    designEthos: 'Sculptural sensuality meeting racing utility. The Daytona SP3 features butterfly doors and a targa roof, with seats integrated directly into the carbon fiber monocoque for an authentic racing position.',
    aeroFeatures: 'Entirely passive aerodynamics utilizing chimney vents on the rear wings to extract low-pressure air, active cooling ducts, and an aggressive rear diffuser.'
  },
  {
    id: 'aston-martin-valkyrie',
    brand: 'Aston Martin',
    model: 'Valkyrie',
    year: 2023,
    price: 3500000,
    priceString: '$3.5 Million',
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    category: 'Track Weapon',
    origin: 'UK',
    engine: '6.5L Naturally Aspirated V12 + KERS Hybrid',
    power: 1139,
    torque: 900,
    topSpeed: 250,
    acceleration: 2.5,
    weight: 1030,
    productionVolume: 150,
    chassis: '100% Carbon Fiber Structure (No metal in chassis)',
    transmission: '7-Speed Automated Single-Clutch',
    drivetrain: 'RWD',
    highlights: [
      'Designed by F1 aerodynamic legend Adrian Newey',
      'V12 engine co-developed with Cosworth revs to 11,100 RPM',
      'Unmatched power-to-weight ratio exceeding 1:1',
      'Extreme Venturi floor tunnels generate astronomical downforce'
    ],
    description: 'Co-created by Aston Martin and Red Bull Racing aerodynamic genius Adrian Newey, the Valkyrie is a Formula 1 car built for the street. Under its tight, carbon fiber shrink-wrapped skin lies a 6.5-liter naturally aspirated Cosworth V12, which screams to an unbelievable 11,100 RPM. This is assisted by a KERS hybrid system, bringing total output to 1,139 hp. It has no luxury items—not even a rear-view mirror (replaced by cameras)—and features a cockpit so tight that drivers require a custom seat fitting.',
    designEthos: 'Extreme minimalism where form strictly follows aerodynamic function. There is not a single flat line; the car is sculpted entirely out of curves designed to manage air.',
    aeroFeatures: 'Full-length underbody venturi tunnels capable of generating up to 1,800 kg of downforce at speed, eliminating the need for a massive high-drag rear wing.'
  },
  {
    id: 'rolls-royce-droptail',
    brand: 'Rolls-Royce',
    model: 'La Rose Noire Droptail',
    year: 2024,
    price: 30000000,
    priceString: '$30.0 Million',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    category: 'Ultra-Luxury',
    origin: 'UK',
    engine: '6.75L Twin-Turbocharged V12',
    power: 593,
    torque: 840,
    topSpeed: 155,
    acceleration: 4.8,
    weight: 2560,
    productionVolume: 4,
    chassis: 'Aluminum Spaceframe (Architecture of Luxury)',
    transmission: '8-Speed Satellite-Aided Automatic',
    drivetrain: 'RWD',
    highlights: [
      'The most expensive new car in modern history',
      'Interior features 1,603 hand-placed wood veneer triangles',
      'Includes a custom, removable Audemars Piguet timepiece on the dash',
      'Paintwork took 150 iterations to perfect a black-cherry hue'
    ],
    description: 'The Rolls-Royce La Rose Noire Droptail is a pinnacle coachbuilt commission, a true rolling sculpture that redefines luxury. Representing a four-year collaboration with a single patron, it is powered by Rolls-Royce’s whisper-quiet 6.75-liter twin-turbo V12. The cabin is an absolute marvel, featuring a wood parquetry design made of 1,603 hand-finished black wood triangles that wrap around the passengers. It includes a custom-commissioned Audemars Piguet watch integrated directly into the dashboard, which can be detached and worn by the owner.',
    designEthos: 'Inspired by the romance of the Black Baccara rose, featuring deep velvet tones and highly dramatic luxury appointments. A removable hardtop roof transforms it from a roadster to a sleek coupe.',
    aeroFeatures: 'Elegant passive aero styling, with a rear deck designed to act as a natural spoiler generating high stability without interrupting the yacht-like silhouette.'
  },
  {
    id: 'porsche-gt3rs',
    brand: 'Porsche',
    model: '911 GT3 RS (992)',
    year: 2023,
    price: 290000,
    priceString: '$290,000',
    image: 'https://images.unsplash.com/photo-1611245801311-1a3f6a27fc17?auto=format&fit=crop&w=1200&q=80',
    category: 'Track Weapon',
    origin: 'Germany',
    engine: '4.0L Naturally Aspirated Flat-6',
    power: 518,
    torque: 465,
    topSpeed: 184,
    acceleration: 3.0,
    weight: 1450,
    productionVolume: 3500,
    chassis: 'Steel-Aluminum Hybrid with Carbon Fiber Panels',
    transmission: '7-Speed PDK Dual-Clutch',
    drivetrain: 'RWD',
    highlights: [
      'Formula 1 style DRS (Drag Reduction System) on the rear wing',
      'Unbelievable 9,000 RPM redline from a racing boxer engine',
      'Individually adjustable rebound and compression dials on the steering wheel',
      'No front luggage compartment—occupied by a massive single radiator'
    ],
    description: 'The Porsche 911 GT3 RS is a street-legal racing car. Eschewing turbos and heavy hybrid systems, Porsche focuses entirely on mechanical handling and extreme, active aerodynamics. Its 4.0-liter naturally aspirated flat-six produces 518 hp and revs to a glorious 9,000 RPM. On the steering wheel are four rotary dials that let you adjust suspension rebound, compression, differential lock-ups, and traction control modes on the fly. Its massive rear wing is higher than the roofline and features an F1-style active DRS button.',
    designEthos: 'Pure motorsport focus. Carbon fiber bucket seats, magnesium wheels, a rear roll cage, and fabric door pulls instead of traditional handles to save weight.',
    aeroFeatures: 'F1-inspired active DRS wing, underbody active air flaps, front fender louvers to relieve wheel arch air pressure, and roof fins to direct hot air away from intake ducts.'
  },
  {
    id: 'mclaren-w1',
    brand: 'McLaren',
    model: 'W1',
    year: 2025,
    price: 2100000,
    priceString: '$2.1 Million',
    image: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80',
    category: 'Hypercar',
    origin: 'UK',
    engine: '4.0L Twin-Turbocharged V8 + High-Power Radial Flux Electric Motor',
    power: 1258,
    torque: 1340,
    topSpeed: 217,
    acceleration: 2.7,
    weight: 1399,
    productionVolume: 399,
    chassis: 'McLaren Aerocell Carbon Fiber Monocoque',
    transmission: '8-Speed Dual-Clutch Automatic',
    drivetrain: 'RWD',
    highlights: [
      'Heir to the legendary McLaren F1 and P1',
      'Ground-effect aerodynamics that lower the chassis by 37mm in race mode',
      'Rear wing extends backwards by 300mm to act as a longtail diffuser',
      'Revolutionary radial flux electric motor spins up to 24,000 RPM'
    ],
    description: 'The McLaren W1 is the spiritual successor to the iconic F1 and P1. Combining an all-new 4.0-liter twin-turbo V8 with a radial flux electric motor, it outputs a mind-melting 1,258 horsepower. What makes the W1 special is its "Active Longtail" aerodynamics, which physically slide the rear wing back by 300mm in Race Mode, shifting the aerodynamic balance to create ground-effect suction. It transfers all its power purely to the rear wheels, making it an intense, high-skill driver’s machine.',
    designEthos: 'Formula 1-inspired teardrop cockpit. The doors are an advanced anhedral design (gullwing-style) that helps channel high-volume air from the front fenders into the radiators.',
    aeroFeatures: 'Active Longtail rear wing, front active wing that sweeps through a large arc, and a fully sculpted, ground-effect carbon fiber floor that behaves like a giant venturi wing.'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'bugatti-tourbillon-hybrid-revolution',
    title: 'The Tourbillon Revolution: Bugatti’s 9,500 RPM Cosworth V16',
    subtitle: 'Inside the engineering masterclass that saved the V16 engine from the jaws of forced induction and absolute hybridization.',
    author: 'Alexander Thorne',
    date: 'June 28, 2026',
    readTime: '6 min read',
    content: [
      'For two decades, Bugatti was synonymous with the W16 engine. Four turbochargers, eight liters of displacement, and a noise like a low-flying jet. But when Mate Rimac took the helm of the legendary French marque, the automotive world braced for an inevitable all-electric future. Instead, Bugatti delivered something far more spectacular, romantic, and technically brave: the Tourbillon.',
      'At the core of the Tourbillon is an entirely new 8.3-liter naturally aspirated V16 engine. Designed in collaboration with Formula 1 engine builder Cosworth, this internal combustion masterpiece revs to an astronomical 9,500 RPM and produces 1,000 horsepower completely on its own. There are no turbos to muffle the sound—just pure, unrestricted mechanical rage escaping through titanium exhaust pipes.',
      'But to meet modern performance targets, Bugatti added a triad of electric motors. Two radial flux motors drive the front wheels, while a third sits at the rear to assist the crankshaft. This provides torque-vectoring all-wheel-drive and adds another 800 hp, culminating in an unbelievable 1,800 hp total. The result is 0-60 mph in 2.0 seconds flat, and a top speed of 276 mph.',
      'The true magic of the Tourbillon, however, lies in its rejection of digital impermanence. Look inside, and you will not find a single screen. Instead, watchmakers from Switzerland have constructed a skeletal gauge cluster out of solid titanium, sapphire crystal, and actual rubies. The needle gears are exposed, meaning you can watch the mechanical linkages spin as you rev the engine. It is an artifact built to last centuries, not just a software lifecycle.'
    ],
    featuredImage: bugattiImg,
    carId: 'bugatti-tourbillon',
    category: 'Engineering',
    tags: ['Bugatti', 'V16', 'Cosworth', 'Horology'],
    likes: 342
  },
  {
    id: 'pagani-utopia-analog-defiance',
    title: 'Analog Defiance: Pagani Utopia and the Art of the Gated Manual',
    subtitle: 'While other manufacturers chase lap times with dual-clutches and high-density battery packs, Horacio Pagani created a sculpture with three pedals.',
    author: 'Giuseppe Rossi',
    date: 'May 14, 2026',
    readTime: '5 min read',
    content: [
      'Walk into any modern hypercar studio, and you will hear a familiar sermon: lap times, active stability algorithms, sub-millisecond shift times, and battery pack pre-conditioning. But walk into San Cesario sul Panaro, the home of Pagani, and Horacio Pagani will tell you about Leonardo da Vinci. He will talk about "Arte e Scienza"—the belief that art and science must walk hand-in-hand.',
      'The Pagani Utopia is a physical manifestation of this philosophy. In an era where manual gearboxes are deemed obsolete for high-horsepower vehicles, Pagani spent millions of dollars engineering a bespoke 7-speed gated manual transmission capable of handling 1,100 Nm of torque from a twin-turbocharged 6.0-liter AMG V12. This is not a paddle-shifter. It has a heavy, mechanical gear stick with its metal shifting mechanism fully exposed in the cabin, clicking like a high-end rifle bolt with every shift.',
      'With only 864 horsepower, the Utopia does not win the modern "top-trumps" horsepower war. But weigh the car, and you realize the truth: it is incredibly light. At 1,280 kg, the Utopia weighs less than a Porsche Cayman. It achieves this through a proprietary carbon-titanium weave that offers immense structural strength without the dead weight of batteries.',
      'Every single detail inside the Utopia is custom-milled. The steering wheel is carved from a single block of aluminum; the dials look like vintage chronograph watches, glowing with soft, warm amber lighting. It is an analog defiance that proves driving engagement is far more luxury than a digital screen will ever be.'
    ],
    featuredImage: paganiImg,
    carId: 'pagani-utopia',
    category: 'Design Language',
    tags: ['Pagani', 'V12', 'Manual', 'Italian Design'],
    likes: 289
  },
  {
    id: 'koenigsegg-jesko-attack-speed-barrier',
    title: 'Cheating Air: How the Jesko Attack Rewrites Aerodynamics',
    subtitle: 'From a carbon fiber chassis to the revolutionary 7-clutch Light Speed Transmission, the Jesko is Swedish engineering in its absolute extreme.',
    author: 'Sven Lindqvist',
    date: 'April 02, 2026',
    readTime: '7 min read',
    content: [
      'In the quiet town of Ängelholm, Sweden, a group of engineers led by Christian von Koenigsegg are doing things with metal and carbon fiber that borders on science fiction. Their latest creation, the Jesko Attack, is designed for one thing: complete track dominance, achieved by mastering the air around it.',
      'The Jesko Attack’s design is dominated by its aerodynamics. The colossal top-mounted active rear wing is curved to follow the contour of the fighter-jet cockpit. Along with a giant front carbon splitter and underbody active flaps, the Jesko produces 1,400 kg of downforce at its top speed—effectively matching its own weight. This means, theoretically, the Jesko could drive upside down on the ceiling of a tunnel.',
      'But how does one harness 1,600 horsepower on a wet track? The secret is the Light Speed Transmission (LST). Standard dual-clutch gearboxes must predict the next gear and shift sequentially. Koenigsegg’s LST features 9 gears and 7 wet multi-disc clutches, meaning it can shift from *any* gear to *any* gear in 2 milliseconds. If you are in 9th gear and stomp the throttle, the car shifts directly to 4th gear instantaneously, bypassing 8th, 7th, 6th, and 5th.',
      'Driving the Jesko is a physical sensory overload. The flat-plane crank 5.0-liter twin-turbo V8 revs so fast it sounds like a superbike, and the active rear-wheel steering stabilizes the chassis at speeds that would make other hypercars squirm. It is a terrifyingly brilliant showcase of Scandinavian engineering.'
    ],
    featuredImage: koenigseggImg,
    carId: 'koenigsegg-jesko',
    category: 'Track Analysis',
    tags: ['Koenigsegg', 'LST', 'Aerodynamics', 'Track Weapon'],
    likes: 412
  }
];
